# Site settings
email: "nemo@nil.foundation"
url: "https://dbms.nil.foundation"
description: ""
areas: 
    - "Authenticated Transaction Log Database Management System"
    - "Your Favorite Database Management System Drop-In Replacement"

meta_author: Mikhail Komarov

titles: 
    - title: "<span style='font-family:Menlo, Courier, monospace'>=nil;</span> Foundation"
      plain: "=nil; Foundation"
      url: "https://nil.foundation"
    - title: "<span style='font-family:Menlo, Courier, monospace'>=nil;</span> Database"
      plain: "=nil; Database"
      url: "https://database.nil.foundation"
    - title: "<span style='font-family:Menlo, Courier, monospace'>=nil;</span> DBMS"
      plain: "=nil; DBMS"
      url: "#page-top"


# Google webmaster tools
# google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: nemo 

# Color settings (hex-codes without the leading hash-tag)
color:
  text-color: F5F2F1
  background-color: 222222
  navbar-color: 222222
  footer-above-color: 222222
  footer-below-color: 222222
  secondary: 907F8F
  secondary-dark: 776475

  background-color-rgb: "37,37,37"

  primary: 725C70
  info: 232125
  success: 57965a
  warning: d58622
  danger: f44336

# Footer settings
footer:
  copyright: =nil; Foundation
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/nil_foundation
    #  - title: facebook
    #    url:
    #  - title: stack-overflow
    #    url: http://stackoverflow.com/questions/tagged/jekyll
    #  - title: bitbucket
    #    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/nilfoundation

# Postal address (add as many lines as necessary)
address:
  - line: Artemis House, 67 Forth Street
  - line: PO Box 2775, Grand Cayman KY1-1111, Cayman Islands

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
